name: Build image

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            arch: amd64
          - target: aarch64-unknown-linux-gnu
            arch: arm64
          - target: armv7-unknown-linux-gnueabihf
            arch: arm
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Cross
        run: |
          curl -SsL https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall cross
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build the binary
        run: |
          RUSTFLAGS="-C target-feature=+crt-static" ~/.cargo/bin/cross build --profile release-lto --target "${{ matrix.target }}"
          mkdir -p binary
          mv "target/${{ matrix.target }}/release-lto/ocitool" binary/
      - name: Upload to registry
        run: |
          cat <<EOF > oci.json
          {
            "name": "ghcr.io/darktohka/ocitool",
            "tags": ["latest"],
            "config": {
              "entrypoint": ["/ocitool"],
              "workingDir": "/",
              "labels": {
                "org.opencontainers.image.source": "https://github.com/darktohka/ocitool"
              }
            },
            "platforms": [
              {
                "architecture": "${{ matrix.arch }}",
                "layers": [
                  {
                    "type": "dir",
                    "source": "./binary",
                    "comment": "https://github.com/darktohka/ocitool"
                  }
                ]
              }
            ]
          }
          EOF
          docker run -v $(pwd):/srv ghcr.io/darktohka/ocitool --username "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.GITHUB_TOKEN }}"